# ############################ #
# PicqBotX 插件启动器 配置文件 #
#     作者: Hykilpikonna       #
# 对应版本: 1.3.3.129          #
# ############################ #

# 连接设置
ConnectionSettings:

  # 监听端口 (HTTP服务器端口)
  ListeningPort: 31092

# 账号设置
Accounts:

  # 第一个账号 (这里是账号名, 可以随便写)
  Account1:

    # 发送地址
    PostURL: '127.0.0.1'

    # 发送地址的端口
    PostPort: 31091

# 指令设置
CommandSettings:

  # 是否启动指令功能
  Enable: true

  # 是否启用异步 (实验性)
  Async: true

  # 指令前缀
  Prefixes:
  - 'bot -'
  - '!'
  - '/'

  # 两个插件同时注册一个指令的话怎么办
  #   ENABLE_LAST    : 启用最后注册的
  #   ENABLE_ALL     : 启用所有
  # 如果冲突的话, 可以用 /<插件名>:<指令> 来执行某个插件的指令
  ConflictOperation: ENABLE_ALL

# 插件加载设置
PluginLoaderSettings:

  # 是否启动插件加载
  Enable: true

  # 插件目录
  PluginDir: './plugins/'

# 日志设置
LoggerSettings:

  # 是否输出Debug日志
  Debug: false

  # 颜色支持级别
  #   FORCED       : 不传入Jansi, 强制启用颜色
  #   PASSTHROUGH  : 实际效果和FORCED一样, 传入Jansi但是不处理
  #   PRESET_ONLY  : 只输出预设颜色, 移除RGB
  #   DEFAULT      : 默认支持
  #   OS_DEPENDENT : 取决于OS, 如果是Linux就用DEFAULT, 如果是Windows就用PRESET_ONLY
  ColorSupportLevel: OS_DEPENDENT

  # Log文件输出目录 (相对目录)
  LogFileRelativePath: logs

  # Log文件名
  LogFileName: PicqBotX-Log

# 其他设置
OtherSettings:

  # HyExp表达式设置
  HyExpression:

    # 是否替换
    Resolve: false

    # 是否安全模式
    SafeMode: true
Access Token: ''
Secret: ''